### ISSUE TITLE
Freemius Theme Check errors

### ISSUE THREAD

**Issue by Prelc** [Prelc/Purus-WP#7]
Theme Check errors:

http://www.awesomescreenshot.com/image/1691532/0a3c913c59436907c190eccc4416ec23

**Comment by primozcigler** [comment]
Contacted original developers of https://github.com/Freemius/wordpress-sdk (@vovafeldman specifically) for help and some explanation.

**Comment by vovafeldman** [comment]
@Prelc @primozcigler we started to work on the changes, should be ready in a day/two.

**Comment by vovafeldman** [comment]
@Prelc @primozcigler I'm excited to let you know that we made all the required changes including a rewrite of the SDK connectivity layer to `wp_remote_request()` to pass **Theme Check** tests and be compliant for the .org themes repo. 

Please pull the latest version from here:
https://github.com/freemius/wordpress-sdk/tree/feature/fs-theme-mode-v2

Let me know if you have any questions.

**Comment by Prelc** [comment]
@vovafeldman Thanks a lot for your effort. This looks great now.

I will make update during this week and let you know if everything is ok after that.

**Comment by vovafeldman** [comment]
Hey @Prelc, just checking if you had the chance to push the update?

**Comment by Prelc** [comment]
Hi @vovafeldman, sorry, I didn't yet manage to update it. I hope I will find time tomorrow.

**Comment by Prelc** [comment]
Hey @vovafeldman, with @primozcigler's help I pushed update a few minutes ago and it went through theme check. I must still wait for the update to go live but it looks like that's it. Thanks!

**Comment by vovafeldman** [comment]
@Prelc that's great news 👍  Keep me posted on your experience.

**Comment by Prelc** [comment]
@vovafeldman It looks like everything is working great now. Overnight I get first users to opted-in and it nicely shows all the data. Thanks again for your hard work.
